databases:
  - name: adam

services:
  - type: web
    name: TwitterApp
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: adam
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false